### ISSUE TITLE
Busybox & SU install broken on update 77

### ISSUE THREAD

**Issue by ebramanti** [linux-shield/shield-root#1]
When I rerooted a clean install of update 77 Busybox and SuperSU did not install whatsoever. After manually installing and updating the apps, root worked fine.

**Comment by Gnurou** [comment]
Sorry, could you elaborate on the issue? Is it that this rooting method doesn't work with Lollipop anymore? I would expect that sadly. How have you managed to root your device?

**Comment by millenniumccdc** [comment]
Yes quite a long time ago. I have version 4.4.2 and root with unlocked
bootloader. Reformatted my 64 class 10 to FAT.

**Comment by ebramanti** [comment]
@Gnurou I've just been using SuperSU for a long time now. Works out of the box.

**Comment by Gnurou** [comment]
@jadengore sorry, this is still not clear to me - what is working out of the box, SuperSU or this rooting method? Does SuperSU now officially support SHIELD?

**Comment by ebramanti** [comment]
@Gnurou Yes, SuperSU officially supports Nvidia Shield. I just flash it in custom recovery.

**Comment by Gnurou** [comment]
Ok, put a link to SuperSU in the project description and mentioned this is obsolete. There is no more reason for this project to exist, outside of educational reasons (that won't apply to lollipop and later anyway)

**Comment by ebramanti** [comment]
@Gnurou Thanks for all your early work tho!
